import type {
  AgentWorkflow,
  Approval,
  Control,
  EvidenceItem,
  FrameworkRequirement,
  GraphEdge,
  GraphNode,
  Integration,
  KnowledgeAnswer,
  PolicyArtifact,
  RbacGrant,
  RemediationItem,
  Vendor,
} from "./types";

export const controls: Control[] = [
  {
    id: "CTRL-PAM-001",
    tenantId: "tenant-acme-us",
    name: "Privileged Access Management",
    description: "Administrative access to production systems is brokered through a managed vault, requires MFA, and records every privileged session.",
    owner: "sec-ops@company.com",
    team: "Security Operations",
    type: "Preventative",
    automation: "Agentic",
    status: "Implemented",
    frameworkCoverage: 92,
    evidenceFreshness: 96,
    assets: ["AWS IAM", "Okta Workforce", "Production Admin Vault"],
    requirements: ["NIST CSF PR.AA-01", "ISO 27001 A.5.16", "SOC 2 CC6.2"],
    evidence: ["EV-PAM-LOGIN-774", "EV-OKTA-MFA-112"],
    riskScenarios: ["Unauthorized admin access to production"],
    indicators: [
      { label: "MFA coverage", value: "99.2%", trend: "up", intent: "good" },
      { label: "Standing admins", value: "4", trend: "down", intent: "good" },
      { label: "Overdue reviews", value: "0", trend: "flat", intent: "good" },
    ],
    fair: { strength: 91, lefReduction: 0.62, plmReduction: 0.18, aleP10: 110000, aleP50: 480000, aleP90: 1400000 },
    lastAgentReview: "2026-07-29 21:44",
  },
  {
    id: "CTRL-VULN-004",
    tenantId: "tenant-acme-us",
    name: "Critical Vulnerability Remediation",
    description: "Critical vulnerabilities on internet-facing production assets are remediated or formally risk accepted within the approved SLA.",
    owner: "platform-risk@company.com",
    team: "Platform Engineering",
    type: "Corrective",
    automation: "Partially Automated",
    status: "Degraded",
    frameworkCoverage: 78,
    evidenceFreshness: 71,
    assets: ["AWS Security Hub", "Container Registry", "Jira Vulnerability Queue"],
    requirements: ["NIST CSF ID.RA-01", "NIST CSF PR.PS-02", "ISO 27001 A.8.8"],
    evidence: ["EV-SHUB-FINDING-991"],
    riskScenarios: ["Exploit of public workload"],
    indicators: [
      { label: "Critical open", value: "7", trend: "up", intent: "bad" },
      { label: "SLA miss", value: "2", trend: "up", intent: "bad" },
      { label: "Patch velocity", value: "68%", trend: "down", intent: "warn" },
    ],
    fair: { strength: 63, lefReduction: 0.28, plmReduction: 0.09, aleP10: 520000, aleP50: 1700000, aleP90: 5200000 },
    lastAgentReview: "2026-07-29 22:09",
  },
  {
    id: "CTRL-TPRM-002",
    tenantId: "tenant-acme-us",
    name: "Tier 1 Vendor Security Review",
    description: "Tier 1 vendors are assessed before onboarding and annually thereafter using SOC 2, security questionnaire, breach history, and data processing scope.",
    owner: "vendor-risk@company.com",
    team: "Third-Party Risk",
    type: "Detective",
    automation: "Partially Automated",
    status: "In Progress",
    frameworkCoverage: 66,
    evidenceFreshness: 58,
    assets: ["Vendor Portal", "Contract Repository", "Data Inventory"],
    requirements: ["NIST CSF GV.SC-06", "ISO 27001 A.5.19", "SOC 2 CC9.2"],
    evidence: ["EV-VENDOR-SOC2-331"],
    riskScenarios: ["Vendor breach exposes customer data"],
    indicators: [
      { label: "Reviews due", value: "11", trend: "up", intent: "warn" },
      { label: "SOC 2 parsed", value: "74%", trend: "up", intent: "good" },
      { label: "DPA gaps", value: "3", trend: "flat", intent: "warn" },
    ],
    fair: { strength: 72, lefReduction: 0.35, plmReduction: 0.14, aleP10: 290000, aleP50: 950000, aleP90: 3100000 },
    lastAgentReview: "2026-07-29 17:31",
  },
  {
    id: "CTRL-EVID-007",
    tenantId: "tenant-acme-us",
    name: "Immutable Evidence Retention",
    description: "Control evidence is written to object-locked storage with version identifiers, hash validation, retention policy, and graph edge traceability.",
    owner: "grc-platform@company.com",
    team: "GRC Platform",
    type: "Preventative",
    automation: "Fully Automated",
    status: "Implemented",
    frameworkCoverage: 88,
    evidenceFreshness: 94,
    assets: ["S3 Object Lock Bucket", "Neptune Graph", "Audit Evidence API"],
    requirements: ["NIST CSF GV.OV-03", "ISO 27001 A.5.37", "SOC 2 CC7.2"],
    evidence: ["EV-S3-WORM-812"],
    riskScenarios: ["Evidence tampering undermines audit attestation"],
    indicators: [
      { label: "Locked objects", value: "100%", trend: "flat", intent: "good" },
      { label: "Hash mismatches", value: "0", trend: "flat", intent: "good" },
      { label: "Versioned edges", value: "98%", trend: "up", intent: "good" },
    ],
    fair: { strength: 89, lefReduction: 0.54, plmReduction: 0.31, aleP10: 80000, aleP50: 260000, aleP90: 840000 },
    lastAgentReview: "2026-07-29 20:17",
  },
];

export const graphNodes: GraphNode[] = [
  { id: "CTRL-PAM-001", kind: "Control", label: "Privileged Access Management", subtitle: "Control", status: "Implemented" },
  { id: "CTRL-VULN-004", kind: "Control", label: "Critical Vulnerability Remediation", subtitle: "Control", status: "Degraded" },
  { id: "CTRL-TPRM-002", kind: "Control", label: "Tier 1 Vendor Security Review", subtitle: "Control", status: "In Progress" },
  { id: "AWS IAM", kind: "Asset", label: "AWS IAM", subtitle: "Asset", status: "Connected" },
  { id: "Okta Workforce", kind: "Asset", label: "Okta Workforce", subtitle: "Asset", status: "Connected" },
  { id: "NIST CSF PR.AA-01", kind: "Requirement", label: "NIST PR.AA-01", subtitle: "Requirement", status: "Active" },
  { id: "ISO 27001 A.5.16", kind: "Requirement", label: "ISO A.5.16", subtitle: "Requirement", status: "Active" },
  { id: "EV-PAM-LOGIN-774", kind: "Evidence", label: "CloudTrail MFA Log", subtitle: "Evidence", status: "Active" },
  { id: "Unauthorized admin access to production", kind: "Risk", label: "Unauthorized Admin Access", subtitle: "Risk scenario", status: "Active" },
  { id: "Evidence Agent", kind: "Agent", label: "Evidence Agent", subtitle: "AI agent", status: "Active" },
  { id: "Acme Payments", kind: "Vendor", label: "Acme Payments", subtitle: "Tier 1 vendor", status: "Active" },
  { id: "POL-PAM-STD", kind: "Policy", label: "PAM Standard", subtitle: "Policy", status: "Pending" },
];

export const graphEdges: GraphEdge[] = [
  { id: "edge-1", from: "CTRL-PAM-001", to: "AWS IAM", label: "IMPLEMENTED_ON", state: "Active", narrative: "AWS IAM roles require MFA and session recording for privileged access." },
  { id: "edge-2", from: "CTRL-PAM-001", to: "Okta Workforce", label: "IMPLEMENTED_ON", state: "Active", narrative: "Okta supplies identity telemetry and MFA state." },
  { id: "edge-3", from: "CTRL-PAM-001", to: "NIST CSF PR.AA-01", label: "SATISFIES", state: "Active", confidence: 94, narrative: "PAM and SSO controls satisfy identity and credential management for authorized users." },
  { id: "edge-4", from: "CTRL-PAM-001", to: "ISO 27001 A.5.16", label: "SATISFIES", state: "Pending Approval", confidence: 86, narrative: "Covers identity management but needs service account scope confirmation." },
  { id: "edge-5", from: "CTRL-PAM-001", to: "EV-PAM-LOGIN-774", label: "PROVED_BY", state: "Active", narrative: "CloudTrail event shows successful MFA for privileged console session." },
  { id: "edge-6", from: "CTRL-PAM-001", to: "Unauthorized admin access to production", label: "MITIGATES", state: "Active", narrative: "Reduces loss event frequency by limiting unauthorized privileged sessions." },
  { id: "edge-7", from: "CTRL-PAM-001", to: "Evidence Agent", label: "EVALUATED_BY", state: "Active", narrative: "Evidence Agent reviewed telemetry using schema-validated prompt context." },
  { id: "edge-8", from: "Acme Payments", to: "CTRL-TPRM-002", label: "RELIED_UPON_FOR", state: "Active", confidence: 88, narrative: "The payment processor's SOC 2 controls are relied on for Tier 1 vendor security review evidence." },
  { id: "edge-9", from: "POL-PAM-STD", to: "CTRL-PAM-001", label: "GOVERNS", state: "Pending Approval", confidence: 91, narrative: "Draft PAM standard maps operating requirements and review cadence to the control." },
];

export const approvals: Approval[] = [
  {
    id: "APR-1042",
    controlId: "CTRL-PAM-001",
    requirementId: "ISO 27001 A.5.16",
    action: "Create SATISFIES edge",
    confidence: 86,
    coverage: 81,
    submittedAt: "2026-07-29 22:18",
    state: "Pending",
    requirementContext: "Identity information must be managed across the full lifecycle for users, services, and privileged access.",
    controlContext: "All administrative access to production systems is managed through PAM and Okta MFA. User lifecycle controls are covered; service identity rotation is adjacent.",
    matchingEvidence: ["privileged access", "MFA", "identity lifecycle"],
    reasoning: "The control strongly covers human privileged access but does not fully describe non-human service credentials. Recommend approval with a linked gap for service accounts.",
  },
  {
    id: "APR-1047",
    controlId: "CTRL-VULN-004",
    requirementId: "NIST CSF PR.PS-02",
    action: "Update coverage to 78%",
    confidence: 73,
    coverage: 78,
    submittedAt: "2026-07-29 22:33",
    state: "Pending",
    requirementContext: "Software is maintained, replaced, and removed commensurate with risk.",
    controlContext: "Critical vulnerabilities on internet-facing production assets are remediated or risk accepted within SLA.",
    matchingEvidence: ["critical vulnerabilities", "remediated", "risk accepted"],
    reasoning: "The control covers remediation of vulnerable software but does not establish software end-of-life replacement criteria.",
  },
];

export const evidenceItems: EvidenceItem[] = [
  {
    id: "EV-PAM-LOGIN-774",
    controlId: "CTRL-PAM-001",
    name: "Privileged console login with MFA",
    type: "System Log",
    method: "API Hook",
    source: "AWS CloudTrail",
    collectedAt: "2026-07-29 21:44",
    validUntil: "2026-10-27",
    s3VersionUri: "s3://ollie-evidence/prod/pam/cloudtrail-774.json?versionId=4f9a",
    hash: "sha256:8fd9d1b1c0a49e27",
    verdict: "Implemented",
    reasoning: "Telemetry shows LoginSuccess for privileged role and mfa_verified=true.",
  },
  {
    id: "EV-SHUB-FINDING-991",
    controlId: "CTRL-VULN-004",
    name: "Critical public workload finding",
    type: "API Telemetry",
    method: "Agent",
    source: "AWS Security Hub",
    collectedAt: "2026-07-29 22:09",
    validUntil: "2026-08-05",
    s3VersionUri: "s3://ollie-evidence/prod/vuln/securityhub-991.json?versionId=9ac2",
    hash: "sha256:a044c9258bbf120e",
    verdict: "Degraded",
    reasoning: "Finding status is New, severity is Critical, and remediation SLA has already elapsed.",
  },
];

export const agentWorkflows: AgentWorkflow[] = [
  {
    id: "agent-evidence",
    name: "Evidence & Telemetry Agent",
    status: "Healthy",
    serviceAccount: "ollie-evidence-agent@grc-prod",
    modelVersion: "reasoning-model-2026-07",
    allowedActions: ["UPDATE_STATUS", "CREATE_EDGE:PROVED_BY", "WRITE_EVIDENCE_HASH"],
    deniedActions: ["DELETE_NODE:*", "CREATE_EDGE:SATISFIES", "UPDATE_RISK_ALE"],
    steps: ["Validate common telemetry envelope", "Retrieve control context", "Evaluate against strict prompt", "Write immutable evidence", "Create PROVED_BY edge"],
    metrics: { toolCalls: 1248, avgTraversalDepth: 1.4, failedValidations: 3, tokensToday: 1842000 },
  },
  {
    id: "agent-risk",
    name: "FAIR Risk & Health Agent",
    status: "Watching",
    serviceAccount: "ollie-risk-agent@grc-prod",
    modelVersion: "reasoning-model-2026-07",
    allowedActions: ["READ_CONTROL_HEALTH", "RUN_MONTE_CARLO", "UPDATE_RISK_ALE"],
    deniedActions: ["DELETE_NODE:*", "CREATE_EDGE:PROVED_BY", "APPROVE_MAPPING"],
    steps: ["Watch degraded controls", "Traverse MITIGATES edges", "Translate telemetry into FAIR variables", "Run simulation", "Publish percentile exposure"],
    metrics: { toolCalls: 312, avgTraversalDepth: 2.2, failedValidations: 1, tokensToday: 612000 },
  },
  {
    id: "agent-framework",
    name: "Framework Mapping Agent",
    status: "Healthy",
    serviceAccount: "ollie-mapping-agent@grc-prod",
    modelVersion: "reasoning-model-2026-07",
    allowedActions: ["CREATE_EDGE:SATISFIES_PENDING", "UPDATE_CONFIDENCE_SCORE", "CREATE_GAP"],
    deniedActions: ["DELETE_NODE:*", "ACTIVE_WITHOUT_APPROVAL", "UPDATE_EVIDENCE_HASH"],
    steps: ["Embed requirement", "Retrieve available controls", "Score coverage", "Generate reasoning", "Route low-confidence edges to approval"],
    metrics: { toolCalls: 532, avgTraversalDepth: 1.8, failedValidations: 7, tokensToday: 923000 },
  },
];

export const integrations: Integration[] = [
  { id: "int-aws", name: "AWS Security Hub", category: "Cloud", status: "Connected", mappedControls: 18, quickWin: "7 controls validated from Security Hub findings." },
  { id: "int-okta", name: "Okta Workforce", category: "Identity", status: "Connected", mappedControls: 12, quickWin: "MFA and lifecycle evidence auto-linked." },
  { id: "int-jira", name: "Jira", category: "Workflow", status: "Available", mappedControls: 6, quickWin: "Cut remediation tickets from failed controls." },
  { id: "int-qualys", name: "Qualys VMDR", category: "Vulnerability", status: "Needs Attention", mappedControls: 9, quickWin: "Replace manual vulnerability evidence pulls." },
  { id: "int-vendor", name: "Vendor Trust Portal", category: "Vendor", status: "Available", mappedControls: 5, quickWin: "Parse SOC 2 reports into control mappings." },
];

export const frameworkRequirements: FrameworkRequirement[] = [
  {
    id: "NIST CSF GV.SC-06",
    framework: "NIST CSF 2.0",
    functionArea: "Govern",
    text: "Suppliers and third-party partners are known, prioritized, and managed based on cyber risk.",
    mappedControls: ["CTRL-TPRM-002"],
    coverage: 66,
    gap: "Annual reassessment cadence is present; continuous vendor monitoring is pending.",
    approvalState: "Pending",
  },
  {
    id: "NIST CSF PR.AA-01",
    framework: "NIST CSF 2.0",
    functionArea: "Protect",
    text: "Identities and credentials for authorized users, services, and hardware are managed.",
    mappedControls: ["CTRL-PAM-001"],
    coverage: 92,
    gap: "Service account lifecycle evidence should be split into its own implementation edge.",
    approvalState: "Active",
  },
  {
    id: "SOC 2 CC7.2",
    framework: "SOC 2",
    functionArea: "System Operations",
    text: "The entity monitors system components and detects anomalies that could indicate malicious acts.",
    mappedControls: ["CTRL-EVID-007", "CTRL-VULN-004"],
    coverage: 84,
    gap: "Connector outage handling needs test evidence before audit freeze.",
    approvalState: "Active",
  },
  {
    id: "ISO 27001 A.8.8",
    framework: "ISO 27001",
    functionArea: "Technology",
    text: "Information about technical vulnerabilities is obtained, evaluated, and addressed.",
    mappedControls: ["CTRL-VULN-004"],
    coverage: 78,
    gap: "Patch replacement criteria and end-of-life exception workflow are not fully mapped.",
    approvalState: "Pending",
  },
];

export const vendors: Vendor[] = [
  {
    id: "VEN-ACME-PAY",
    name: "Acme Payments",
    tier: "Tier 1",
    dataAccess: "Customer payment metadata",
    businessOwner: "finance-ops@company.com",
    assessmentStatus: "Due Soon",
    externalRating: "B+ stable",
    reliedUponControls: ["CTRL-TPRM-002", "CTRL-EVID-007"],
    riskSignal: "SOC 2 bridge letter expires in 21 days.",
  },
  {
    id: "VEN-CLOUD-ID",
    name: "Cloud Identity Labs",
    tier: "Tier 1",
    dataAccess: "Workforce identities and MFA state",
    businessOwner: "it-ops@company.com",
    assessmentStatus: "Current",
    externalRating: "A improving",
    reliedUponControls: ["CTRL-PAM-001"],
    riskSignal: "No material exceptions in latest assessment.",
  },
  {
    id: "VEN-SCAN-CO",
    name: "ScanCo VM",
    tier: "Tier 2",
    dataAccess: "Asset metadata and vulnerability telemetry",
    businessOwner: "platform-risk@company.com",
    assessmentStatus: "Blocked",
    externalRating: "C watch",
    reliedUponControls: ["CTRL-VULN-004"],
    riskSignal: "API scope missing container registry findings.",
  },
];

export const policyArtifacts: PolicyArtifact[] = [
  {
    id: "POL-PAM-STD",
    title: "Privileged Access Management Standard",
    type: "Standard",
    owner: "sec-ops@company.com",
    status: "In Review",
    approvedVersion: "v0.3 draft",
    mappedControls: ["CTRL-PAM-001"],
    lastUpdated: "2026-07-30",
  },
  {
    id: "POL-EVID-SOP",
    title: "Immutable Evidence Handling SOP",
    type: "SOP",
    owner: "grc-platform@company.com",
    status: "Approved",
    approvedVersion: "v1.0",
    mappedControls: ["CTRL-EVID-007"],
    lastUpdated: "2026-07-29",
  },
];

export const remediations: RemediationItem[] = [
  {
    id: "REM-221",
    playbook: "Open Jira remediation ticket",
    trigger: "Critical vulnerability SLA breach",
    controlId: "CTRL-VULN-004",
    asset: "Internet-facing workload",
    riskTier: "High",
    approvalGate: "Analyst approval required before status reversal",
    status: "Awaiting Approval",
  },
  {
    id: "REM-228",
    playbook: "Request vendor bridge letter",
    trigger: "Tier 1 vendor assessment due soon",
    controlId: "CTRL-TPRM-002",
    asset: "Acme Payments",
    riskTier: "Medium",
    approvalGate: "TPRM analyst review",
    status: "Recommended",
  },
  {
    id: "REM-230",
    playbook: "Rotate stale service credential",
    trigger: "Identity lifecycle gap",
    controlId: "CTRL-PAM-001",
    asset: "AWS IAM service role",
    riskTier: "Mission Critical",
    approvalGate: "Second approver and change window",
    status: "Recommended",
  },
];

export const rbacGrants: RbacGrant[] = [
  { role: "Admin", globalFair: "Yes", graphAccess: "Full tenant", evidence: "Upload/export", approvals: "Approve all", guardrails: "Modify" },
  { role: "Analyst", globalFair: "Yes", graphAccess: "Full tenant", evidence: "Upload/export", approvals: "Approve mappings", guardrails: "Read-only" },
  { role: "Owner", globalFair: "No", graphAccess: "Assigned controls", evidence: "Upload assigned", approvals: "No", guardrails: "No" },
  { role: "TPRM", globalFair: "Vendor scope", graphAccess: "Vendor graph", evidence: "Upload vendor", approvals: "Vendor scope", guardrails: "No" },
  { role: "Executive", globalFair: "Yes", graphAccess: "Read-only", evidence: "No", approvals: "No", guardrails: "No" },
  { role: "Auditor", globalFair: "Scoped", graphAccess: "Scoped read-only", evidence: "Export package", approvals: "No", guardrails: "No" },
];

export const knowledgeAnswers: KnowledgeAnswer[] = [
  {
    id: "KMS-001",
    question: "What controls are failing for public production assets?",
    answer: "Critical Vulnerability Remediation is degraded because Security Hub evidence shows critical findings past SLA.",
    confidence: 89,
    graphPath: ["CTRL-VULN-004", "IMPLEMENTED_ON", "AWS Security Hub", "PROVED_BY", "EV-SHUB-FINDING-991"],
    queryPreview: "MATCH (c:Control)-[:IMPLEMENTED_ON]->(a:Asset)-[:PROVED_BY]->(e:Evidence) WHERE c.status = 'Degraded'",
  },
  {
    id: "KMS-002",
    question: "Which policies govern privileged access evidence?",
    answer: "The PAM Standard draft governs CTRL-PAM-001, which is proved by CloudTrail MFA evidence and reviewed by the Evidence Agent.",
    confidence: 92,
    graphPath: ["POL-PAM-STD", "GOVERNS", "CTRL-PAM-001", "PROVED_BY", "EV-PAM-LOGIN-774"],
    queryPreview: "MATCH (p:PolicyDocument)-[:GOVERNS]->(c:Control)-[:PROVED_BY]->(e:Evidence) WHERE c.id = 'CTRL-PAM-001'",
  },
];
